export const FILE_UPLOAD  = {
    TYPES: {
        JPG: ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tga', 'tif', 'tiff'],
        DOC: ['text', 'doc', 'docx', 'odt'],
        XLS: ['xls', 'xlsx', 'ods'],
        PPT: ['ppt', 'pptx', 'odp'],
        TXT: ['plain', 'txt', 'log'],
        AVI: ['mp4', 'avi', 'mov', 'wmv', 'mpg', 'flv'],
        ZIP: ['rar', 'zip', '7z', 'gzip', 'gz', 'zipx'],
        PDF: ['pdf'],
        HTML: ['html'],
        JS: ['javascript'],
        JAVA: ['java'],
        XML: ['xml'],
    },

    ICONS: {
        JPG: 'icon-file-image-o',
        DOC: 'icon-file-word-o',
        XLS: 'icon-file-excel-o',
        PPT: 'icon-file-powerpoint-o',
        TXT: 'icon-file-text-o',
        AVI: 'icon-file-video-o',
        ZIP: 'icon-file-archive-o',
        PDF: 'icon-file-pdf-o',
        HTML: 'icon-html5',
        JS: 'icon-file-text-o',
        JAVA: 'icon-file-text-o',
        XML: 'icon-file-text-o',
        DEFAULT: 'icon-file',
    },
};
